Test runner: prevent double-registration of tests
There is a problem with `unittest` SQLlogic runner that, when tests are
run from the extension repo directory, extension tests from under
`test/sql` can be registered twice. First they are registered from under
the relative `test` directory and the second time from [ExtensionHelper::LoadedExtensionTestPaths()](https://github.com/duckdb/duckdb/blob/a93109abaed85521e4199770f6ff205aa6995a87/extension/generated_extension_loader.cpp.in#L25)
that is generated at configure-time and contains `TEST_DIR` argument
passed to `duckdb_extension_load` CMake function.

There is no tests deduplication on registration:

 - if `TEST_DIR` is specified as `test` or `test/sql` then the runner
   fails with:

```
error: TEST_CASE( "test/sql/storage/attach_simple.test" ) already defined.
    First seen at /home/alex/projects/duckdb-sqlite/duckdb/test/sqlite/test_sqllogictest.cpp:41
    Redefined at /home/alex/projects/duckdb-sqlite/duckdb/test/sqlite/test_sqllogictest.cpp:41
```

 - if `TEST_DIR` is not specified, the absolute path
   `/path/to/extension/repo/test/sql` is used for it; that results into
   the test to be registered twice - once on relative path and once on
   absolute path.

The problem is not severe, when the test runner is invoked with a
pattern argument like this (used in most cases):

```
./build/release/unittest 'test/*'
```

Then only relative path-registered tests are run.

But the problem stil remains with `.test_slow`. Such tests are registed
with `[.]` group label. The double registration problem makes it
impossible (at least I didn't find the way without additional
`require-env`) to run all tests once excluding `.test_slow` (that is
desired for ASan/TSan test runs):

 - `./build/release/unittest` - runs tests (excluding `.test_slow`)
   twice
 - `./build/release/unittest 'test/*'` - runs test once, but does not
   exclude `.test_slow`
 - `./build/release/unittest '~[.]'` (Catch2 group negation) - runs
   tests (excluding `.test_slow`) twice

This PR attempts to detect that relative `test/sql` path and
`ExtensionHelper::LoadedExtensionTestPaths()` path are resolved to the
same path and skip the second registration.