Add windows_undefs to a multi-file reader header
On Window with MSVC the `interface` is defined as a macro:

```c++
```

We have the [undef header](https://github.com/duckdb/duckdb/blob/3cb65aa794b4c985a98493f188fb58db79a370f8/src/include/duckdb/common/windows_undefs.hpp#L46-L48)
for that, but it is not applied everywhere.

In unity builds after some recent inclusion changes in
`ub_src_common.cpp` the build started failing on Windows with:

```
multi_file_states.hpp(69): error C2236: unexpected token 'struct'. Did you forget a ';'?
```

This PR adds the under header to `multi_file_states.hpp` that fixes the
problem.