let julia use system's libstdc++ in CI
By default julia should have bundled a libstdc++ in
a place like `/usr/lib/julia/libstdc++.so.6`, while
`libduckdb.so` is built with system's glibc usually
in `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`, set
the `LD_PRELOAD` variable may let julia and duckdb use
the same version of glibc to avoid errors like

```
ERROR: LoadError: could not load library "/home/runner/work/duckdb/duckdb/build/release/src/libduckdb.so"
/opt/hostedtoolcache/julia/1.7.3/x64/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/runner/work/duckdb/duckdb/build/release/src/libduckdb.so)
```